[project]
name = "student"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic[email]>=2.11.7",
    "python-multipart>=0.0.20",
    "uvicorn>=0.35.0",
]
